部署pytorch

diff --git a/.github/workflows/deploy_web_site.yml b/.github/workflows/deploy_web_site.yml
--- a/.github/workflows/deploy_web_site.yml
+++ b/.github/workflows/deploy_web_site.yml
@@ -35,40 +35,42 @@ jobs:
       #     fetch-depth: 1
       #     submodules: true
       # Checkout other repo    
-      - name: Checkout other repo
+      - name: 检出其他仓库Checkout other repo
         uses: actions/checkout@v4
         with:
-          repository: linjonh/TechBlog
-          branch: main
+          repository: linjonh/ffmpeg-docs-website
+          branch: pytorch_tutorial_website
           fetch-depth: 0
-          path: TechBlog
+          token: ${{ secrets.PAT_TOKEN }}
+          path: pytorch-tutorial
       - name: List checked out files
         run: |
-          ls -alh TechBlog || echo "TechBlog not found" 
-          cd TechBlog
+          ls -alh pytorch-tutorial || echo "pytorch-tutorial not found" 
+          cd pytorch-tutorial
           git branch -a
-          git checkout -b main origin/main
+          git checkout -b pytorch_tutorial_website origin/pytorch_tutorial_website
           ls -alh
-      #build
-      - name: Set up Ruby
-        uses: ruby/setup-ruby@v1
-        with:
-          ruby-version: '3.4.2' # 替换为你项目实际使用的版本
-          bundler-cache: true
-      # Install ruby dependencies
-      - name: Install dependencies and build site
-        run: |
-          pwd
-          ls -lh
-          cd TechBlog
-          git branch -a
-          git checkout main
-          gem install bundler
-          bundle install --jobs 4 --retry 3
-          # build site
-          bundle exec jekyll build -d "_site" --trace
-        env:
-          JEKYLL_ENV: production
+      # #build
+      # - name: Set up Ruby
+      #   uses: ruby/setup-ruby@v1
+      #   with:
+      #     ruby-version: '3.4.2' # 替换为你项目实际使用的版本
+      #     bundler-cache: true
+      
+      # # Install ruby dependencies
+      # - name: Install dependencies and build site
+      #   run: |
+      #     pwd
+      #     ls -lh
+      #     cd TechBlog
+      #     git branch -a
+      #     git checkout main
+      #     gem install bundler
+      #     bundle install --jobs 4 --retry 3
+      #     # build site
+      #     bundle exec jekyll build -d "_site" --trace
+      #   env:
+      #     JEKYLL_ENV: production
       #Setup pages
       - name: Setup Pages
         id: pages
@@ -77,7 +79,7 @@ jobs:
       - name: Upload site artifact
         uses: actions/upload-pages-artifact@v3
         with:
-          path: "TechBlog/_site"
+          path: "pytorch-tutorial/html_zh_CN"
   deploy:
     environment:
       name: github-pages
